pipeline {
  agent any

  stages {
    stage('Build') {
      steps {
        sh 'mvn clean install'
      }
    }
    stage('Deploy to Tomcat') {
      steps {
        // Deploy WAR to Tomcat
        sh 'mvn tomcat7:deploy'
      }
    }
  }

  post {
    always {
      // Post-build actions (e.g., cleanup, notifications)
      cleanWs() // Clean workspace
      // Add other actions here (e.g., email notifications)
    }
    success {
      // Actions to run on success
    }
    failure {
      // Actions to run on failure
    }
  }
}
