pipeline {
    agent any
    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', 
                    url: 'https://github.com/ArnavMurdande/DevOps-Lab-Practice.git'
            }
        }
        stage('Run Ansible Playbook') {
            steps {
                dir('ansible-jenkins-demo') {
                    ansiblePlaybook(
                        playbook: 'playbook.yml',
                        inventory: 'inventory.ini',
                        extras: '--become'
                    )
                }
            }
        }
    }
}
